version: '3.8'
services:
  db:
    image: mysql:5.7
    container_name: local-db
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    restart: always
    environment:
      - MYSQL_ROOT_
  json-server:
    build: ./json-server
    container_name: json-server-container
    ports:
      - '3001:3000'
    volumes:
      - ./json-server/data/data.json:/data/data.json
    command: json-server --watch data.json --host 0.0.0.0
  react-crud:
    build: ./react-crud
    container_name: react-curd-container
    ports:
      - '4000:4000'
    stdin_open: true
