version: '3.8'
services:
  json-server:
    build: ./json-server
    container_name: json-server-container
    ports:
      - '3001:3000'
    volumes:
      - ./json-server/data/data.json:/data/data.json
    command: json-server --watch data.json --host 0.0.0.0
  react-crud:
    build: ./react-crud
    container_name: react-curd-container
    ports:
      - '4000:4000'
    stdin_open: true
